name: Build Releases

on: push

jobs:
  build-job:
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: npm install

      - run: npm run compile_css

      - name: Build Unix
        run: sudo node .github/workflows/build_distributables.js
        if: matrix.os != 'windows-latest'

      - name: Build Windows
        run: node .github/workflows/build_distributables.js -RunAsAdmin
        if: matrix.os == 'windows-latest'

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          append_body: true
          files: |
            ./out/*
